### ISSUE TITLE
Jak dodać całą mapke

### ISSUE THREAD

**Issue by Daewo147** [lpiob/MTA-XyzzyRP#108]
Witajcie, wyłączyłem już resources lss-mapa, ale czasami jest tak że nagle gdzieś mnie teleportuje jak wejde np. do wody. Więc pytanie jest jak włączć całą mapkę (domyślnie jest tylko LS i parę miasteczek pobocznie)

**Comment by MichAu1** [comment]
po usunięciu miałem błąd i pisało bym sie skontaktował z administratorem :P moze w inny sposób sie da jakoś dodać?
