### ISSUE TITLE
Jak dodać marker dla gangu oraz jak usunąć wszelkie napisy/loga XyzzyRP i panel pod F1

### ISSUE THREAD

**Issue by krinek** [lpiob/MTA-XyzzyRP#117]
1. Witam, zrobiłem gang, wszystko dobrze tylko nie mam markera w którym mogę dodawać/wyrzucać ludzi z gangu, zmieniać rangi itp. Jak go stworzyć? W bazie danych czy FTP? W jakim pliku? 
2. Jak usunąć ten napis XyzzyRP z okienka "Pobieranie zasobów", z panelu logowania i zamienić na własne logo? Jeszcze w MTA, w wyszukiwarce, obok nazwy serwera jest zakładka "Gamemode" jak zmienić tam napis z "XyzzyRP" na własny?
3. Jak dać komuś Supportera/Admina i zmienić hasło dla admina. Jak loguje się na admina to wpisuje /login root tester. A jak zmienić hasło "tester" na własne? I np. Kolega gra na moim serwerze, to jak mu dać admina/suppa?
4. Jak zmienić szyfr do sejfów frakcji. Np. Jestem burmistrzem to jak zmienić szyfr do sejfu w UM? Tak samo z innymi frakcjami
5. Jak usunąć te "stalowe" śmieci z Grove? Jak się na nie wjedzie pojazdem to go rozwala. Pozbierałem wszystko, wyrzuciłem gdzieś i po jakimś czasie powracają. Kilka razy tak robiłem.
6. Jak naprawić to: ![beztytuu](https://f.cloud.github.com/assets/5400191/2240935/44e7696e-9cb6-11e3-9316-0db5689e1bc2.png)

**Comment by Kanapke** [comment]
A jak mam dobrze połączyć DB itp
