### ISSUE TITLE
jak wgrać moduł mta_mysql.so

### ISSUE THREAD

**Issue by dawid2a** [lpiob/MTA-XyzzyRP#144]
http://pastebin.com/4UxVs6av 
kolejny błąd, prawdopodobnie podczas łączenia z bazą danych. Wszystko jest robione na maszynie dedykowanej z phpmyadmin na localhoscie, w obu plikach podałem dokladnie te same dane do logowania bazy danych oraz zaimportowałem baze.

**Comment by Roshi94** [comment]
te modułu ogl są do wywalenia stare i nie działają dlatego tyle ludzi ma z tym problemy
