### ISSUE TITLE
Panel rejestracji in- game

### ISSUE THREAD

**Issue by druch5** [lpiob/MTA-XyzzyRP#234]
Czytałem że ma zostać wprowadzona rejestracja postaci in-game. 
https://github.com/lpiob/MTA-XyzzyRP/issues/102

Kiedy zostanie to wprowadzone?

**Comment by V6N2** [comment]
W najbliższym czasie zamierzam to wydać, obserwuj mojego gita ;)

**Comment by druch5** [comment]
ok :)
