### ISSUE TITLE
import

### ISSUE THREAD

**Issue by tom99925** [lpiob/MTA-XyzzyRP#241]
jak naprawić tą lukę w kodzie żeby samochody przypływały na statku a nie żeby się spawniły w hangarze

**Comment by TheAdrik2** [comment]
To nie luka. Możesz to robić poprzez import (IC) i komendę.

**Comment by tom99925** [comment]
Nie chodzi mi o to żeby wprowadzać dane jakie samochody itp bo to wiem jak robić mi chodzi o lukę która blokuje przypływ samochodów na statku bo one się spawnują w hangarze a statek miga a chce żeby statek się zatrzymał i na nim samochody były żeby to było bardziej realu a nie ze się pokazują w hangarze jak by nigdy nic

**Comment by tom99925** [comment]
ref
