### ISSUE TITLE
Wielebny(Proszę abyś przeczytał)

### ISSUE THREAD

**Issue by TRIN123** [lpiob/MTA-XyzzyRP#249]
Witam,serdecznie Wielebny!
Mam pytanie czy podał byś swój skype oraz gg?

**Comment by TheAdrik2** [comment]
Wielebny nie czyta tych pytań. A nawet jeśli to i tak Ci nie poda Skype'a. (Nikt już nie używa GG)

**Comment by Grigusny** [comment]
Alez wiele osob uzywa gg, nawet sam zainteresowany xD

**Comment by lpiob** [comment]
Czytam, ale nie odpowiadam na pytania czy odpowiem na pytanie. Jak masz jakąś sprawę, to po prostu pisz.  Mój adres e-mail jest podany w wielu plikach w tym repozytorium.
