### ISSUE TITLE
Kurierzy

### ISSUE THREAD

**Issue by tom99925** [lpiob/MTA-XyzzyRP#259]
Mam takie pytanie gdzie znajde markery zeby kurierzy rozwozili paczki przez gps nie chodzi mi o prace dorywcza tylko o firme kurierska bo wie ze niektorzy by to przeczytali i by mysleli ze mi chodzi o prace dorywcza a tak nie odbiegajac z teamtu to szukam gdzie sa te markery ogolnie zebym mogl aktywowac kurierow ze oni do celow przez gps rozworza na odpowiedz z gory dziekuje

**Comment by piotr172** [comment]
Wpisz na serwerze /start lss-spedycja i skrypt się włączy.

**Comment by tom99925** [comment]
dzieki
