### ISSUE TITLE
EQ

### ISSUE THREAD

**Issue by tom99925** [lpiob/MTA-XyzzyRP#262]
Mam pytanie dlaczego jak wchodzę to mi pokazuje na chacie napis "EQ 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0" itd nie wiem co mam z tym zrobić

**Comment by piotr172** [comment]
Wejdź w plik resources/[XyzzyRP]/lss-core/ekwipunek.lua i w 237 linijce usuń to:
outputChatBox("EQ " .. eq.eq)
Zapisz plik i restartuj skrypt lss-core na serwerze.
