### ISSUE TITLE
Panel IN-GAME. Sprzedam!

### ISSUE THREAD

**Issue by piotr172** [lpiob/MTA-XyzzyRP#267]
Witam, mam do sprzedania panel tworzenia konta IN-GAME oraz postaci do gamemodu Xyzzy-RP. Panel prezentuje się w taki oto sposób(filmik): https://youtu.be/_w9WGRTrNYE (polecam oglądać w jakości 720p)
FORMA PŁATNOŚCI: PSC, cena do uzgodnienia.
KONTAKT: Skype:piotr000024 w treści zaproszenia proszę pisać "Panel Xyzzy-RP" wtedy na pewno przyjmę zaproszenie.

**Comment by haracz1234** [comment]
Tu jest all za darmo wiec po co kupowac :d http://game-web.pl/

**Comment by piotr172** [comment]
Tylko tam jest samo gui i to nie działa...

**Comment by haracz1234** [comment]
Zaktualizowany został.

**Comment by tom99925** [comment]
dziala wszystko tam
