### ISSUE TITLE
Transport pojazdów lawetą

### ISSUE THREAD

**Issue by vonflynee** [lpiob/MTA-XyzzyRP#268]
Witam,
Czy istnieje możliwość transportu osobówek lawetą (packer)?
Wjeżdżam na lawetę pojazdem, lecz gdy ruszę, zsuwa się on z lawety.
Kiedy zaciągnę w nim ręczny, samochód zostaje w powietrzu.
Jak zablokować pojazd na lawecie?

Pozdrawiam i życzę miłego dnia,
vf

**Comment by piotr172** [comment]
Jeżeli chodzi o Lawete jako DFT-30 to jest możliwość taka, wchodzi się na pake i naciska na nią i wtedy jest Zablokuj koła, a na Packerze z tego co jest mi wiadomo nie ma takiej możliwości. I do DFT potrzebna jest podmianka: http://www.gtagarage.com/mods/show.php?id=12893
