### ISSUE TITLE
Problem z odblokowaniem miast

### ISSUE THREAD

**Issue by Mefisek** [lpiob/MTA-XyzzyRP#278]
Witam mój problem polega na tym że: nie moge oblokować miast LV/SF na autostradzie są kamienie po wylaczeniu ich trace rondo itp. nie mam ulic mam tylko wode.

Prosił bym o informacje co mam robic lub na skype/gg

Skype:mefisization

GG:47851972

**Comment by lpiob** [comment]
https://github.com/lpiob/MTA-XyzzyRP/issues/108

**Comment by Mefisek** [comment]
Przykro mi ale to nie działa

**Comment by MichAu1** [comment]
u mnie tez nie działa. to tylko uszkadza serwer :D
