### ISSUE TITLE
Jak dodać przedmioty dla frakcji?

### ISSUE THREAD

**Issue by druch5** [lpiob/MTA-XyzzyRP#283]
Witajcie, mam pytanie jak zrobić żeby policjanci dostawali broń i amunicje przy rozpoczęciu pracy? Bo dostają pager, kluczyki itp.

**Comment by luki2407** [comment]
lss-frakcja > frakcje.lua 

Znajdź

    elseif (factionid==2) then	-- policja 	-- 7 pda 11 klucze
	exports["lss-core"]:eq_takeItem(source, 35)	-- pager
	exports["lss-core"]:eq_giveItem(source,35,1)

	exports["lss-core"]:eq_takeItem(source, 7)	-- pda
	exports["lss-core"]:eq_giveItem(source,7,1)


Dodaj

   exports["lss-core"]:eq_takeItem(source, 115)	
   exports["lss-core"]:eq_giveItem(source,115,1)     - ID Broni > Ilość

W linii 330 robisz to samo :)

**Comment by druch5** [comment]
Bardzo dziękuje za pomoc.
