### ISSUE TITLE
Problem z domkami 

### ISSUE THREAD

**Issue by luczak11211** [lpiob/MTA-XyzzyRP#294]
Witam,mam problem iż są pozamykane biznesy takie jak: OSK w bazie danych zmieniam aby były otwarte czyli zmieniam liczbę z 1-0 i na odwrót i nic dodam że w innych biznesach to działa mogę zrobić by były zamknięte/otwarte proszę o pomoc ;(

**Comment by luczak11211** [comment]
Jakby to był jakiś bug dodam też że nie wszystkie domki które są ponoć otwarte są zamknięte ;(

**Comment by piotr172** [comment]
Sprawdź date do której jest opłacony ten domek/biznes, po prostu może minęła data opłacenia tego i dlatego jest zamknięty.

**Comment by luczak11211** [comment]
Rozwiązane ;)
