### ISSUE TITLE
Jak zmienić położenie neonów w poszczególnych autach?

### ISSUE THREAD

**Issue by GabWas** [lpiob/MTA-XyzzyRP#299]
Mam problem z neonami, mianowicie w niektórych autach są one w środku albo w ogóle odstają od niego. Jak zmienić ich położenie? Jaki plik za to odpowiada? Z góry dzięki.

**Comment by Jaccck** [comment]
https://github.com/lpiob/MTA-XyzzyRP/blob/master/resources/%5BXyzzyRP%5D/lss-vehicles/vehicles.lua
Linia 474

**Comment by GabWas** [comment]
Czekając na odpowiedź już sam zdążyłem to rozkminić, jednak dzięki za fatygę :-)
