### ISSUE TITLE
Frakcja - dodwanie.

### ISSUE THREAD

**Issue by luczak11211** [lpiob/MTA-XyzzyRP#308]
Witam, korzystałem z filmiku jak dodać do frakcji itp itd Użytkowinika Piotra, lecz nic to nie daje. Robię wszytsko tak jak jest na filmie ;( Realodowałem all pliki serwerowe i też nic.

Proszę o pomoc. Może w skrypcie jest coś zwalone ;(

**Comment by Mefisek** [comment]
zaraz ci dam wzór jak to powinno wyglądać

**Comment by Mefisek** [comment]
[img]http://i.imgur.com/5QbHBlQ.jpg[/img]

**Comment by Mefisek** [comment]
<blockquote class="imgur-embed-pub" lang="en" data-id="5QbHBlQ"><a href="//imgur.com/5QbHBlQ">View post on imgur.com</a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by luczak11211** [comment]
A mam pytanie jeszcze ;( Jak wchodzisz na posterunek i tam masz marker za drzwiami to jak je otworzyć xD? bo rozwiązanie mam jedno żeby zmienić kordy blipu

**Comment by Mefisek** [comment]
Tab i prawym na drzwi i otworz lub jak nie dziala to zaloguj sie jako root i wpisz /thru 2

**Comment by luczak11211** [comment]
O jezu jaki ja głupi ;( Close ;D

**Comment by Mefisek** [comment]
Nic sie nie stalo każdemu zdarza sie nie wiedziec :)
