### ISSUE TITLE
Mam do Sell paczke neonów 

### ISSUE THREAD

**Issue by Mefisek** [lpiob/MTA-XyzzyRP#309]
Tak jak wyżej jeśli ktoś chce obejżeć te neony zapraszam na gg:47851972

**Comment by Mefisek** [comment]
Obejrzec sr literowka :P

**Comment by GabWas** [comment]
Niech zgadnę, wyciągnąłeś modele z plików SA-MP'a i chcesz je sprzedawać?

**Comment by Diskej** [comment]
Ja mam na sell Neony i all Podmianki pod Xyzy RP np na Kamizelki pod PD all za darmo !!

**Comment by Mefisek** [comment]
Diksej napisz na gg wezme :ap

**Comment by extrm91** [comment]
diskej można ?
