### ISSUE TITLE
Prawo jazdy pytanie

### ISSUE THREAD

**Issue by luczak11211** [lpiob/MTA-XyzzyRP#312]
Witam, mam problem OSK 1 i OSK 2 pokazuje mi w bazie danych że to jest L1 i L2, chodzi mi o to że jak mam zrobić prawo jazdy (mam serwer testowy) chciałbym się podszkolić w LUA i mi to pomaga ;)

Na kat b mam wyjeździć 10 min lecz jak mam dodać instruktora jak nie ma tego w bazie? ;(

**Comment by GabWas** [comment]
Aby wyrobić prawo jazdy kat. B, nie musisz podchodzić do żadnych egzaminów. Wystarczy przejechać 10 minut w aucie Club z pasażerem obok. Twórcy trochę nie dopracowali tego skryptu, ponieważ pasażer nie musi być we frakcji OSK, co oznacza że tak naprawdę dowolna osoba może obok Ciebie siedzieć.
Jeżeli jednak chcesz kogoś tam dodać, wystarczy że zajrzysz do phpMyAdmin, otworzysz tabelę `lss_character_factions` oraz klikniesz na zakładkę "Wstaw". Następnie w polu `character_id` wpisz ID postaci, w polu `faction_id` wpisz 8 (OSK1) lub 16 (OSK2), a w polu `rank` wpisz liczbę od 1 do 5 (kolejno są to: Pomocnik, Instruktor, Kierownik, Z-ca Dyrektora, Dyrektor). Klikasz "Wykonaj" i gotowe.

**Comment by luczak11211** [comment]
A powiedz mi jak mogę podpiąć paliwo itp pod licznik?

**Comment by GabWas** [comment]
Nie za bardzo wiem co masz na myśli, rozwiń swoje pytanie.

**Comment by luczak11211** [comment]
No ten system paliwa podpiać pod licznik ;( Wiem że się da tylko nie wiem jak hehe

Zeby dodać do licznika system paliwa

**Comment by Jaccck** [comment]
Przecież domyślnie licznik paliwa jest podpięty.

**Comment by luczak11211** [comment]
Własnie nie ;( (chyba że ja tak mam) mam tylko licznik km/h i kilometry ;(

**Comment by luczak11211** [comment]
Chyba że on nie aktywuje sie przy zrespionych pojazdach ;p

**Comment by GabWas** [comment]
Licznik paliwa jest dostępny tylko w prywatnych pojazdach z ID, ponieważ stan baku jest zapisywany w bazie danych, a w pojazdach "zrespionych" jest to nie do wykonania, dlatego się nie wyświetla.

**Comment by luczak11211** [comment]
Łe ;p A tak wgl to jak mam kupić pierwszy pojazd? Bo tak noł oriejnt

**Comment by GabWas** [comment]
Skorzystaj z komendy `/sv [ID modelu pojazdu]`.

**Comment by luczak11211** [comment]
Kluczyki dostaję a gdzie pojazd? ;(

**Comment by Jaccck** [comment]
./ttv id_pojazdu

**Comment by luczak11211** [comment]
Okej, to już mam ;)

Da się zrobić by automatycznie dawało inną rejke np LS 1 itp?

I czy można zrobić tzw cygana z autami? na tym GM?

**Comment by lpiob** [comment]
@GabWas 
> Licznik paliwa jest dostępny tylko w prywatnych pojazdach z ID, ponieważ stan baku jest zapisywany w bazie danych, a w pojazdach "zrespionych" jest to nie do wykonania, dlatego się nie wyświetla.

Do pojazdu zrespionego w innym zasobie wystarczy dodać `setElementData(pojazd, "paliwo", { a, b })` aby nadać mu zbiornik o rozmiarze `b`, zapełniony do `a`.

**Comment by GabWas** [comment]
@lpiob 

> Do pojazdu zrespionego w innym zasobie wystarczy dodać setElementData(pojazd, "paliwo", { a, b }) aby nadać mu zbiornik o rozmiarze b, zapełniony do a.

W sumie racja, nie pomyślałem o elementDacie :smile:

**Comment by Jaccck** [comment]
@luczak11211

Na rejestracji pojazdu standardowo jest ustawiony` 'LS ID_POJAZDU'` jesli chciałbyś na przykład zmianę na `'SF ID_POJAZDU'` wystarczy ze w bazie danych, w tabel `lss_vehicles` zmienisz domyślną wartość 'tablica', z LS na SF.

Można, wystarczy że w tym zasobie https://github.com/lpiob/MTA-XyzzyRP/tree/master/resources/%5BXyzzyRP%5D/%5Bobiekty%5D/nieuzywac-salonsamochodowy poustawiasz sobie auta i włączysz zasób.

**Comment by luczak11211** [comment]
Jacku, chodziło mi o rejestracje np 58TI HFJ Mam dać gdzieś pojazd by zrobiła sie rejka SF?

**Comment by Jaccck** [comment]
Wystarczy zapewne przeładować pojazdy lub sam reset skryptu i powinno nadać.
