### ISSUE TITLE
Pytanie o przechowywalnie

### ISSUE THREAD

**Issue by luczak11211** [lpiob/MTA-XyzzyRP#316]
Witam, czy jest możliwość stworzenia przechowywalni chociażby takiej co jest na Pylife? Czy jest to nie wykonalne?

**Comment by GabWas** [comment]
Skoro jest na PYLife to chyba jest wykonalna, nie sądzisz? Nie licz na gotowce.

**Comment by luczak11211** [comment]
No tak, nie liczę na gotowce

Tylko że zrobienie skryptu do jakiś mały problem na gtao.pl mi pomogą w razie czego.
Tylko ja bym musiał tą przechowywalnie pod bazę podpiąć czy jak? ;p

**Comment by GabWas** [comment]
Przejrzyj [pliki przechowalni](https://github.com/lpiob/MTA-XyzzyRP/tree/master/resources/[XyzzyRP]/[obiekty]/lss-przechowalnia_aut) załączonej w GM'ie.

**Comment by luczak11211** [comment]
Nie widzę żeby wgl była połączona, ta przechowywalnia to ten taki parking na autostradzie? jeśli mnie pamięć nie myli ;p (taki parking na wodzie coś w tym stylu?) jeśli tak, to mi się wgl brama nie otwiera ;(

**Comment by luczak11211** [comment]
local wynik=exports.DB:pobierzWyniki(query)

o co chodzi z tym pobieraniem? to jest o bazy?

**Comment by GabWas** [comment]
@luczak11211 
> Nie widzę żeby wgl była połączona, ta przechowywalnia to ten taki parking na autostradzie? jeśli mnie pamięć nie myli ;p (taki parking na wodzie coś w tym stylu?) jeśli tak, to mi się wgl brama nie otwiera ;(

Ona nie ma się otwierać. Zostawiasz auto przez bramą (masz tam wyznaczony prostokąt), podchodzisz do automatu (żółta budka) i wybierasz odpowiednią opcję.

> local wynik=exports.DB:pobierzWyniki(query)
> o co chodzi z tym pobieraniem? to jest o bazy?

Jest to zapytanie, dzięki któremu skrypt pobiera odpowiednie dane z MySQL.

**Comment by luczak11211** [comment]
Czasem rzecz banalna jest, najtrudniejsza ;) dziękówa ;D
