### ISSUE TITLE
Problem z respem pojazdów - zamknięte

### ISSUE THREAD

**Issue by luczak11211** [lpiob/MTA-XyzzyRP#317]
A więc tak zrespiłem sobie auto komendami sv itp

i są zamknięte drzwi ;(

[img]http://i.imgur.com/5FYCnzB.jpg[/img]

Ktoś wie w czym tkwi problem?

**Comment by GabWas** [comment]
Człowieku, najpierw ogarnij podstawy tego gamemode'a i przestań zakładać codziennie po kilka nowych zgłoszeń...
TAB -> PPM na aucie -> Otwórz drzwi.

**Comment by luczak11211** [comment]
Myślisz że nie próbowałem?...

**Comment by luczak11211** [comment]
Dobra, zamykam to. Problem rozwiąże sam.
