### ISSUE TITLE
Ikony panel f1 i tablice

### ISSUE THREAD

**Issue by luczak11211** [lpiob/MTA-XyzzyRP#319]
Witam, mam parę pytań.

Czy jest możliwość zamiany tych kwadracików w ls na mapie na jakieś ikony?
2.Jak edytować tablice?
3 Jak edytować panel f1?

**Comment by GabWas** [comment]
Jeju, człowieku, wysil się chociaż trochę i pogrzeb w kodzie. Jeżeli nie masz pojęcia o niczym, to się za to po prostu nie bierz...
2. Edytujesz je w bazie danych, tabela `lss_infoboards`.
3. Folder `lss-pomoc`. Albo zedytuj sobie `przewodnik.lua`, albo otwórz folder `pomoc` i jakiś plik *.xml.

**Comment by luczak11211** [comment]
Poradziłem sobie.
