### ISSUE TITLE
Pomoc.

### ISSUE THREAD

**Issue by Kacper890** [lpiob/MTA-XyzzyRP#320]
Witam, proszę Łukasz Biegaj o kontakt na skype. Albo kogoś kto bardzo dobrze zna się na XyzzyRP. Pozdrawiam.

**Comment by Mefisek** [comment]
Z tego co wiem to lukasz nie podaje priv komunikatorów

**Comment by GabWas** [comment]
Z pewnością biegnie do Ciebie zadzwonić, bo przecież nie ma nic lepszego do roboty.
Zamknij to zgłoszenie i napisz nowe opisując tam swój problem, a postaramy się Ci pomóc.

**Comment by Mefisek** [comment]
Właśnie do mnie napisał ze masz mu podać adres.Rzuca wszystko,prace , żone  i juz do ciebie biegnie.

**Comment by Kacper890** [comment]
Zamykam.
