### ISSUE TITLE
Bład ServerProject

### ISSUE THREAD

**Issue by Kacper890** [lpiob/MTA-XyzzyRP#324]
Problem polega na tym, że po restarcie sewera nie mogę go włączyć. Wciskam przycisk i wychodzi komunikat, że się włączył a tak naprawdę jest Offline.. Pomoże ktoś ?

**Comment by GabWas** [comment]
Odśwież stronę. Często jest tak, że po wyskoczeniu komunikatu i kliknięciu `OK`, strona za szybko się odświeża i serwer "jest offline".
