### ISSUE TITLE
Dlaczego nie mam wszystkich komend?

### ISSUE THREAD

**Issue by Kacper890** [lpiob/MTA-XyzzyRP#326]
Nie działają mi komendy takie jak /thv. Jak komuś się zbuguje auto to co ja mam zrobić ? da się to jakoś naprawić ? i czy da się dodać Panel Admina dla rangi Admini?
Jak dodać nowe rangi: Pracownik Techniczny, RCON?

**Comment by XyzzyMaster** [comment]
thv nie jest domyślnie wgrane, napisz własny skrypt

**Comment by Jaccck** [comment]
Może czas się zapoznać chociaż trochę z językiem panującym w MTA? Jeśli planujesz otworzyć serwer - raczej będziesz musiał się z nim trochę zapoznać - polecam [podstawowy poradnik](https://wiki.multitheftauto.com/wiki/Scripting_Introduction).
