### ISSUE TITLE
Jak dodać blipy

### ISSUE THREAD

**Issue by Kacper890** [lpiob/MTA-XyzzyRP#327]
Jak dodać blipy żeby były na całej mapce ?

**Comment by GabWas** [comment]
Nie związane z gamemode'm, zapraszam do zapoznania się z funkcją [createBlip](https://wiki.multitheftauto.com/wiki/CreateBlip) w MTA.

**Comment by Kacper890** [comment]
Ale jak to dodać ;P

**Comment by GabWas** [comment]
Wszystko jest opisane w podanym przeze mnie linku. Są tam nawet przykładowe użycia tych funkcji.
Jeżeli nie znasz się na LUA, to czas może je poznać. Polecam przeczytać [podstawowy poradnik](https://wiki.multitheftauto.com/wiki/Scripting_Introduction).

**Comment by Kacper890** [comment]
Dzięki, pomogłeś :+1:
