### ISSUE TITLE
Bugi Xyzzy-RP?!

### ISSUE THREAD

**Issue by Kacper890** [lpiob/MTA-XyzzyRP#331]
Witam, zgłaszam się z bugiem XyzzyRP? dlaczego zwykły gracz blokuje dostęp do logowanie i rejestrowania ? ma dostęp do lss-core? jak to zrobić. Już kilka razy ten typ rozwalił mi serwer.

**Comment by XyzzyMaster** [comment]
Opisz dokładniej problem, sprawdz pliki DB i DB2 czy są poprawnie podłączone z bazą.

**Comment by Kacper890** [comment]
nie wiem jak to opisać, po prostu taki typ zablokował mi rejestracje i logowanie jak on to zrobił? podobno jest jakiś bug XyzzyRP, że można coś zrobiś chyba w lss-gui albo w lss-core

**Comment by Jaccck** [comment]
./login tester tester <- jeżeli koncie 'tester' nie odebrałeś praw administratora, zrób to przed wdrożeniem. Tak samo zmień sól z MRFX_01 na swoją własną.

**Comment by Kacper890** [comment]
> Tak samo zmień sól z MRFX_01 na swoją własną.

> 
O co z tym chodzi?

**Comment by Jaccck** [comment]
Dlatego właśnie popieram technike najpierw zapoznaj się dobrze z kodem potem zadawaj pytania. Jest to sól dodawana do haseł - aby jeszcze bardziej zabezpieczyć konta graczy przed wyciekiem. Aby zmienić sól używaną aktualnie na koncie musisz wykonać zapytanie 

`UPDATE lss_users SET hash=MD5(CONCAT(LOWER(login),'tu_wpisz_swoja_sol','tu_wpisz_nowe_haslo')) WHERE id=1;`

Oraz w każdym skrypcie odwołującym się do autoryzacji gracza zmienić trzeba sól MRFX_01 na własną

**Comment by Kacper890** [comment]
Ehh nie rozumiem tego...

**Comment by Kacper890** [comment]
Podpowiesz chociaż gdzie te zapytanie zrobić?

**Comment by Jaccck** [comment]
No jak to gdzie? w MySQL, pamiętaj tylko żeby najpierw edytować autoryzacje po stronie serwera (zmienić sól). Jeśli najpierw zmienisz sól tylko w swoim haśle (na konto tester) nie będziesz się mógł na nie zalogować.

**Comment by Kacper890** [comment]
No i właśnie taki przypadek teraz - nic nie zrobiłem tylko restart serwera i znów się nie mogę zalogować...

**Comment by Kacper890** [comment]
Nie wiem o co w tym chodzi...jak zmienić tę autoryzacje ? ehh zdejmę hasło z serwera i ten typ znów rozwali...

**Comment by Jaccck** [comment]
Jeżeli po restarcie serwera nie możesz się zalogować na konto w panelu logowania, nie masz połączenia z bazą danych.
