### ISSUE TITLE
Jak dodać bramę

### ISSUE THREAD

**Issue by Kacper890** [lpiob/MTA-XyzzyRP#334]
Chciałbym dodać bramę do gangu i żeby ona otwierała się dla członków gangu. Jak to zrobić?

**Comment by Jaccck** [comment]
Wzorujesz się na [tym](https://github.com/lpiob/MTA-XyzzyRP/blob/master/resources/%5BXyzzyRP%5D/%5Bobiekty%5D/wb-komis_titanic/brama.lua), dla przykładu zmieniasz tam koordynaty na swoje. Usuwasz zakomentowane tam komendy 'bo' i bz', następnie do brama.otworz=function(), według mnie przed moveObject dodajesz

`local character=getElementData(client,"character") if (character.co_id) == ID_GANGU then `
gdzie w ID_GANGU wpisujesz id gangu dla jakiego ma się otwierać brama.

w brama.zamknij=function() wpisujesz to samo - też przed moveobject. Powinno działać, jeśli nie wstaw błędy z DB3.

**Comment by Kacper890** [comment]
Kiepski ze mnie '' Technik '' i ten plik mam wrzucić do Resources ?

**Comment by Jaccck** [comment]
Podałem zły przykład - zaraz go poprawię.

**Comment by Kacper890** [comment]
Mógłbym prosić o twojego Skype? mam jeszcze kilka pytań z którymi nie mogę sobie poradzić

**Comment by Kacper890** [comment]
Dzięki za pomoc, mógłbym prosić o Twojego Skype?

**Comment by Jaccck** [comment]
Nie używam Skype, pomagam tylko tutaj.
