### ISSUE TITLE
Oszust XyzyRP v2

### ISSUE THREAD

**Issue by Diskej** [lpiob/MTA-XyzzyRP#345]
Witam, dzisiaj o godz 14:15 użytkownik gg o emailu lukgar98@gmail.com, GG:48309807, https://github.com/ghost, https://webmasteruj.pl/user/17396-adminpro/?tab=topics oszukał mojego kolege, nie zdradze nicku, miał dać jemu paczke XyzzyRP v2, lecz po tym jak mu podał kod PSC + wysłał mu pieniądze na serverproject.pl po prostu wyszedł se z GG i do tej pory nie wbił, uważajcie nie kupujcie NIGDY od niego paczek, bo was oszuka tak jak mojego kolegę. ,, **Brain**-- # AdminPRO // sprzedawał # **_las-rp.pl_**  miał obrazek http://imgur.com/cSIHmSS

**Comment by kaMMi21** [comment]
Mnie też frajer chciał oszukać.

**Comment by Diskej** [comment]
to takie kurwa CJ grajom

**Comment by lpiob** [comment]
Oszustwo zgłoś na policję, to przestępstwo za które grozi kara niezależnie od kwoty. Myślę, że policja nie będzie miała żadnych problemów z ustaleniem tożsamości tej osoby.

**Comment by Diskej** [comment]
dobra dzienki
