### ISSUE TITLE
Mapa

### ISSUE THREAD

**Issue by kaMMi21** [lpiob/MTA-XyzzyRP#346]
Mam problem z mapą ponieważ chciałem odblokować całą mapę lecz gdy zrobiłem wszystko tak jak było w innych tematach to nie ma blokad lecz miast też nie tylko światła latranie itp.

**Comment by Diskej** [comment]
podaj skype

**Comment by kaMMi21** [comment]
Nie lepiej TS ?

**Comment by Diskej** [comment]
wole skype :+1:

**Comment by kaMMi21** [comment]
A masz ts bo skype musze pobrać

**Comment by Diskej** [comment]
ok
podaj ts

**Comment by kaMMi21** [comment]
Sekunda

**Comment by kaMMi21** [comment]
i-yw.pl MAX 2 kaMMi
