### ISSUE TITLE
Panel

### ISSUE THREAD

**Issue by Kaczynski34** [lpiob/MTA-XyzzyRP#348]
Witam, otóż zainstalowałem panel od Piotra 172, zarejestrować się mogę, lecz już kliknąć zaloguj, zalozenie postaci nie mogę, proszę o szybką pomoc, Pozdrawiam.

**Comment by Diskej** [comment]
Żle podłączyłeś pod baze danych

**Comment by Kaczynski34** [comment]
Juz naprawilem.

**Comment by Diskej** [comment]
:)

**Comment by XJMLN** [comment]
Jeżeli naprawiłeś - zamknij zgłoszenie.
