### ISSUE TITLE
Baza Danych

### ISSUE THREAD

**Issue by kaMMi21** [lpiob/MTA-XyzzyRP#349]
Mam pytanie czy da się podłączyć inne skrypty pod bazę danych na tym gamemode chodzi o giełde i prace dorywcze. Jeśli tak szukam osoby która to zrobi. ;)

**Comment by XJMLN** [comment]
Wszystko da się podłączyć pod tą bazę danych.

**Comment by kaMMi21** [comment]
A potrafisz to robic ?
