### ISSUE TITLE
Komenda /thv

### ISSUE THREAD

**Issue by Kaczynski34** [lpiob/MTA-XyzzyRP#350]
Witam was, poszukuję komendy /thv jest ona mi bardzo potrzebna do tego gamemode, bo nie chce mi sie kazdego auta po kolei ustawiać.

**Comment by XJMLN** [comment]
To napisz, tutaj ta komenda nie jest zaimplementowana. Długo nie zeszło a komenda jest (około 3 minuty).

function cmd_thv(player,command,vid)
    if (not vid or not tonumber(vid)) then return end
    vid=tonumber(vid)
    for i,v in ipairs(getElementsByType("vehicle")) do
	local dbid=getElementData(v,"dbid")
	local x,y,z = getElementPosition(player)
	if (dbid and tonumber(dbid)==vid) then
	    setElementPosition(v,x,y,z+4)
	    setElementInterior(v, getElementInterior(v))
	    setElementDimension(v, getElementDimension(v))
	    warpPedIntoVehicle(player,v)
	    return
	end
    end
    outputChatBox("Nie odnaleziono na mapie pojazdu o podanym ID.", player, 255,0,0)
	-- sprawdzmy czy nie jest w przechowalni
	local query=string.format("SELECT 1 FROM lss_vehicles WHERE id=%d AND przechowalnia>0",vid);
	local wynik=exports.DB:pobierzWyniki(query)
	if (wynik) then
		outputChatBox("Pojazd znajduje sie na parkingu/w przechowalni.", player)
	end
    return
end

addCommandHandler("thv", cmd_thv, true, false)

**Comment by Kaczynski34** [comment]
A gdzie to mam wgrać ? zrobić nowy plik, i tam wgrać, czy do lss-admin ?

**Comment by XJMLN** [comment]
lss-admin/commands_admin lub commands_support

**Comment by Kaczynski34** [comment]
Dałem to do commands_admin i nie działa.

**Comment by Kaczynski34** [comment]
Nie działa dalej wkleiłem do commands_support i gówno

**Comment by Kaczynski34** [comment]
ALo
Odpowiesz ?

**Comment by XJMLN** [comment]
Dodaj sobie uprawnienia do thv.

**Comment by Kaczynski34** [comment]
A spk

**Comment by XJMLN** [comment]
Jeżeli problem rozwiązany - zamknij zgłoszenie.
