### ISSUE TITLE
[SZUKAM] Szukam ekipy na serwer RP Xyzyrp

### ISSUE THREAD

**Issue by Diskej** [lpiob/MTA-XyzzyRP#354]
Szukam ekipy na serwer RP 
Serwer Jest oparty na GM xyzyRP , dużo tam umiem ale sam rady nie dam to dlatego szukam ludzi 

Wymagane: 
+15, +16 
Ogarnięcie 
Oferuje: 
Współpracę serwerową 
Rangę na serwerze. 

Rangę na serwie to się dogadamy zależy co umiesz i w czym pomożesz 

GG:55689686 
Skype:diskej//obrazek Koleś ?

**Comment by kaMMi21** [comment]
Ooo proszę co ja tu widzę xD

**Comment by kaMMi21** [comment]
Nic Nic xD

**Comment by kaMMi21** [comment]
DisKej frajerze oddwaj skrypty które usunales albo spotkamy się na drodze prawnej.

**Comment by Komel123** [comment]
TO jest same XyzzyRP i z neta WIĘC GÓWNO MU MOŻESZ ZROBIĆ FRAJERZE.

**Comment by Diskej** [comment]
ahhahah xyzyrp + ywg z neta weś spierdalaj

**Comment by kaMMi21** [comment]
Po pierwsze nie same XyzzyRP

**Comment by Diskej** [comment]
o jeju pisałeś że twoje skrypty tak oooo ja sesrałem  sie jak ty nawet kurwa nie umiesz pisac w lua wes speirdalaj

**Comment by kaMMi21** [comment]
Po drugie ogarnij kolegę naucz się ortografii jobany homunculusie i ssij pęto

**Comment by Diskej** [comment]
pęt ahhahahahahahahaahhahh morda

**Comment by Diskej** [comment]
# **Spierdalaj kurwo**

**Comment by Diskej** [comment]
@kaMMi21 CJ

**Comment by kaMMi21** [comment]
Dobra kurwa mam juz twoje IP hosting mi udzieilił więc pozdro ;)

**Comment by Komel123** [comment]
SPierdalaj od niego, łysa pało robiona w Caritasie chuju pierdolony spierdalaj najlepiej, kurwa same XyzzyRP i YWG a ty tu kurwa pierdolisz jak jakis idiota JEbany sukinsynie

**Comment by Diskej** [comment]
kammi okej czekam ja ci zaraz ddos jebne tylko cie odblokuje na skype

**Comment by Komel123** [comment]
Chuj pierdolony KAMMI21 TO PEDAŁ CHUJ PIERDOLONY

**Comment by kaMMi21** [comment]
Komel wypierdalaj ssać jajka ojcu

**Comment by Komel123** [comment]
PIERDOL SIE
ŁYSY CHUJU

**Comment by kaMMi21** [comment]
Boisz się pizdo ?
Że blokujesz ?

**Comment by Diskej** [comment]
ja blokuję tylko debili ;)

**Comment by Komel123** [comment]
O jezu chyba ty masz 10 lat bo od razu na policje.

**Comment by kaMMi21** [comment]
Klej wary lapsie i do kąta siad

**Comment by Komel123** [comment]
Dobra spierdalaj, chuju jebany

**Comment by tokelpl** [comment]
Jezu jak sie spinacie, mialem zamiar pomoc ale jak to przeczytalem
odechcialo mi sie.


W dniu środa, 29 czerwca 2016 Komel123 <notifications@github.com>
napisał(a):

**Comment by Diskej** [comment]
xd
