### ISSUE TITLE
problem z logowaniem po 1 dniu gry

### ISSUE THREAD

**Issue by MichAu1** [lpiob/MTA-XyzzyRP#358]
Witam!. Otóż mam problem. Gdy wgrałem GM wszystko dzialało przez jeden dzień. następnego dnia juz nie mogłem się zalogować ponieważ podczas wybierania postaci wyskskiwało network trouble.
pomoże ktoś?

**Comment by Kaczynski34** [comment]
Zobacz może się zmieniły pasy do bazy danych, albo wgraj inny poprostu panel.

**Comment by MichAu1** [comment]
ogarnąłem wszystko. @lock
