### ISSUE TITLE
auta frakcyjne i ich id w mysql

### ISSUE THREAD

**Issue by MichAu1** [lpiob/MTA-XyzzyRP#363]
czy można dodać auto frakcyjne które nie zmieniało by A_I w bazie danych? problem polega na tym że chciałbym mieć na serwerze prywatne auta od id 1 wzwyż a gdy dodam auto frakcyjne to mi się zmienia auto increment i nie mogę go cofnąć. próbowałem dać id 2000 dla pojazdu frakcyjnego lecz naliczanie id zaczynało się od id 2001 i cofnąć się do id 1 nie mogłem. trochę chaotycznie napisane ale mam nadzieje  ze mnie zrozumieliście.

**Comment by sampak** [comment]
Wejdź w tabele lss-vehicles następnie przejdź do zakładki operacje i AUTO_INCREMENT ustaw na 1
http://puu.sh/q1qny/5285cdb885.png

**Comment by MichAu1** [comment]
właśnie w tym jest problem że jezeli mam auto id 2000 to nie moge ustawic id 1 bo i tak sie zmieni na id 2000+

**Comment by lpiob** [comment]
Nie zmieni się.

**Comment by MichAu1** [comment]
to trudno :/
