### ISSUE TITLE
Reaktywacja LSS-RP

### ISSUE THREAD

**Issue by Neproify** [lpiob/MTA-XyzzyRP#369]
Cześć, piszę do ciebie ponieważ byłeś założycielem LSS-RP. Nie znalazłem do ciebie kontaktu poza githubem. Programuję w LUA, grałem kiedyś na LSS-RP, przez pewien czas pomagałem przy rozwijaniu kodu(czasy gdy już nie zajmowałeś się tym projektem). Chciałbym reaktywować LSS-RP. Wiem że było kilka prób, jednak przez nieudolność i brak chęci (nowej) administracji nie wypaliły. Mógłbym wziąć od ciebie jakiś kontakt poza githubem? @lpiob

**Comment by lpiob** [comment]
Na stronie głównej tego repozytorium jest podany mój adres e-mail.
