### ISSUE TITLE
Panel logowania(kamera)

### ISSUE THREAD

**Issue by slavenx** [lpiob/MTA-XyzzyRP#377]
Witam jak zmienić położenie, poruszanie się kamery w panelu logowania (w jakim pliku to jest)

**Comment by XJMLN** [comment]
lss-gui/intro.lua funkcja renderLoginBox

**Comment by slavenx** [comment]
A którą dokładnie linijke mam dodać/przerobić aby ta kamera pojawiła się w ls i przemieszczała z np urzedu na park przed

**Comment by XJMLN** [comment]
Domyślnie w kodzie kamera jedynie będzie się kręciła dookoła pozycji którą ustawisz - nie będzie się przemieszczała.

Zamieniasz getElementPosition na pozycję gdzie ma być ustawiona ta kamera. Pozycję wklejasz[ tu](https://github.com/lpiob/MTA-XyzzyRP/blob/master/resources/%5BXyzzyRP%5D/lss-gui/intro.lua#L30). Dodatkowo, możesz zmienić [dist] (https://github.com/lpiob/MTA-XyzzyRP/blob/master/resources/%5BXyzzyRP%5D/lss-gui/intro.lua#L32)
