### ISSUE TITLE
Podmianki WAZNE

### ISSUE THREAD

**Issue by slavenx** [lpiob/MTA-XyzzyRP#379]
Witam u kogo najwiarygodniej kupić podmianki do neonów, pojazdów, eq itp

**Comment by XJMLN** [comment]
Przecież podmianki neonów możesz znaleźć **za darmo** na internecie, tak samo wszystkie podmianki.

**Comment by slavenx** [comment]
aha dzieki
P.S. to dlaczego piot172 (moze nick przekrecilem) pisze ze u niego mozna kupic?
