### ISSUE TITLE
Licencja

### ISSUE THREAD

**Issue by slavenx** [lpiob/MTA-XyzzyRP#380]
Czy w jakis sposob moge kupic licencje?

**Comment by lpiob** [comment]
Od jakiegoś czasu kod jest udostępniany na licencji MIT, oznacza to z grubsza tyle że możesz z nim robić co chcesz i wystarczy że napiszesz gdzieś że Twój kod opiera się lub zawiera fragmenty XyzzyRP.

https://github.com/lpiob/MTA-XyzzyRP#chciałbym-się-dowiedzieć-czy-mogę-wraz-ze-znajomym-użyć-całego-kodu-do-stworzenia-nowego-serwera-oraz-jeżeli-tak-czy-możemy-wprowadzić-w-nim-parę-nowych-zmianulepszeń

Jeśli i ten wymóg Ci nie pasuje i chciałbyś zakupić licencję która pozwoli Ci zrobić cokolwiek z kodem, to skontaktuj się proszę ze mną. Za drobną darowiznę na dowolny dom dziecka przekażę Ci licencję na dowolne wykorzystywanie.

**Comment by slavenx** [comment]
A w jaki sposob moge sie z toba skontaktowac?

**Comment by lpiob** [comment]
lukasz.biegaj@gmail.com

**Comment by slavenx** [comment]
napisalem
