### ISSUE TITLE
Szukam technika ZAPLACE

### ISSUE THREAD

**Issue by slavenx** [lpiob/MTA-XyzzyRP#383]
Witam od pewnego czasu bawię się owym gamemodem. Ponieważ w lua mistrzem nie jestem poszukuje osoby która w razie problemów mogła by mi pomóc, zapłacę

**Comment by haracz1234** [comment]
Napisz do mnie na gg 56257440 na pewno sie dogadamy.

**Comment by VVrongVVay** [comment]
15454000 ;)
