### ISSUE TITLE
Dwa Pytania...

### ISSUE THREAD

**Issue by Szydlo** [lpiob/MTA-XyzzyRP#387]
Hej, Pierwsze Pytanie jak się dać sobie kierownika we wszystkich frakcjach i jak zamontować do auto rzeczy typu Audio Big Stard, Biegi Fast,Folia

**Comment by XJMLN** [comment]
Musisz dodać się ręcznie do tych frakcji w bazie danych.
Taki tuning montujesz również ręcznie w bazie danych.
