### ISSUE TITLE
Problem z konfiguracja plikow db i db2

### ISSUE THREAD

**Issue by MisterPL** [lpiob/MTA-XyzzyRP#401]
Witam, potrzebuje pomocy w sprawie konfiguracji plikow db i db2 a dokladnie adresu bazy danych, probowalem wszystkich dostepnych adresow mysql-1.serverproject.pl 3rdp.serverproject.pl oraz localhsot lecz za kazdym razem nie nawiazuje komunikatu z baza danych (korzystam z hostingu serverproject.pl)
oto tak sa skonfigurowane:

DB:

local SQL_LOGIN="db_22542"
local SQL_PASSWD="---"
local SQL_DB="db_22542"
local SQL_HOST="mysql-1.serverproject.pl"
local SQL_PORT=tonumber(get("port") or 3306)

DB2:

   -- w ponizszej linii uzupelnij dane autoryzacji
	SQL = dbConnect("mysql", "dbname=db_22542;host=mysql-1.serverproject.pl", "db_22542","---","share=1")
	if (not SQL) then

**Comment by piotr172** [comment]
Musisz dane wziąć z hostingu. Na serverproject wygląda to tak: [Obrazek](https://camo.githubusercontent.com/1a73185f2e9011945f8a4c2896db6ecdc0b112f0/687474703a2f2f692e696d6775722e636f6d2f30644c335170672e706e67). Musisz przekopiować linijkę "host" i powinno działać. Jak nie to sprawdź czy nie zrobiłeś jakiejś literówki/spacji gdzieś w danych. I czy masz wgrane moduły, bo to też ważna sprawa.

**Comment by MisterPL** [comment]
juz naprawilem , blad lezal w tym ze mialem zainstalowany rowniez plik dll
