### ISSUE TITLE
Podmienianie skinów

### ISSUE THREAD

**Issue by tomadr123** [lpiob/MTA-XyzzyRP#404]
Witam chcę wiedzieć jak zmienić skiny frakcji ? Bo chcę z podmianek wźiąść .

**Comment by XJMLN** [comment]
Chodzi Ci o zamianę ID skina w bazie danych (później to ID jest widoczne w panelu frakcji)?

**Comment by tomadr123** [comment]
Tak

**Comment by tomadr123** [comment]
A dobra nakierowałes mnie. Zamykam
