### ISSUE TITLE
Jak wgrać te skrypty na serwer lokalny na hamahi? 

### ISSUE THREAD

**Issue by Flash3050** [lpiob/MTA-XyzzyRP#406]
Chciałbym se wgrać te wszystkie skrypty na serwer lokalny hamahi, tylko nwm jak to zrobić? chodzi mi o deatchmtch/recoures itp. I jak zrobić aby te skrypty automatycznie się włączały. Chciałbym se pograć zanim założę serwer na hostingu. Proszę o pomoc. Pozdrawiam Flash3050

**Comment by XJMLN** [comment]
Instalacja GM'a na serwerze lokalnym (Windows) przebiega tak samo jak na hostingu. 
Kieruj się wskazówkami zawartymi w https://github.com/lpiob/MTA-XyzzyRP/wiki/Instalacja-XyzzyRP-na-ServerProject.pl

Po wgraniu wszystkiego na serwer, stwórz bazę danych (możesz użyć programu WAMP lub XAMPP), wgraj strukturę i odpal serwer.

**Comment by Flash3050** [comment]
Właśnie trochu tego nie ogarniam tego wgrywania skryptów modeli itp oraz tej bazy danych. Czy mógłbyś zrobić mały poradnik co po koleji albo nagrał mały poradnik dotyczący wgrywania tego całego moda na localu windows? Dziękuje

**Comment by XJMLN** [comment]
Pewnie, film może nie jest jakiś profesjonalny lecz raczej w 100% wytłumaczyłem instalację krok po kroku. 
[Filmik](https://www.youtube.com/watch?v=d9TYTQezPaM) (Film będzie dostępny po przetworzeniu przez YouTube)
Powodzenia w dalszej pracy! :) Pamiętaj o zamknięciu zgłoszenia jeśli temat wyczerpany.

**Comment by Flash3050** [comment]
Dziękuje pozdrawiam
