### ISSUE TITLE
paliwo

### ISSUE THREAD

**Issue by extrm91** [lpiob/MTA-XyzzyRP#411]
witam czy mógł by ktoś z kodem na dodawanie paliwa w pojazdach ?
albo napisał skrypt stacji mogę zapłacić

**Comment by Dzender** [comment]
Witaj, powiem ci tak stacja jest wgrana w xyzzyRP a na dodawanie paliwa jest panel admina ;) Poszukaj tutaj a  znajdziesz ;)
