### ISSUE TITLE
neony tuning

### ISSUE THREAD

**Issue by extrm91** [lpiob/MTA-XyzzyRP#414]
mam pytanie gdzie dodać pliki odpowiedzialne za neony ?

**Comment by Dzender** [comment]
Musisz posiadać podmianke neonów i wgrać ja do folderu podmianki ;)

**Comment by VedaR123** [comment]
dzender dodaj na skype VedaR. miałeś z nami być ale 0 kontaktu coś ostatni :/

**Comment by Dzender** [comment]
@VedaR123 marek.fajny123 Proszę

**Comment by extrm91** [comment]
mam pliki col, txd i dff

**Comment by Dzender** [comment]
Wgrywasz to do podmianek. I powinno działać .
