### ISSUE TITLE
Koguty

### ISSUE THREAD

**Issue by VedaR123** [lpiob/MTA-XyzzyRP#416]
Witam jak dodać koguty do pojazdu ? bo gdy dodaję go w tabeli to po włączeniu koguta wyświetla się : (( zakładanie koguta na ten model pojazdu nie jest oprogramowane, zglos to administracji )) wie ktoś o co cmn ?

**Comment by Dzender** [comment]
Ta kogut nie jest zapisany na danym aucie musisz sam to zrobic i ustalić pozycję koguta

**Comment by VedaR123** [comment]
ale gdzie to ustawić mój przyjacielu ? i jak wgrać podmianke koguta ?

**Comment by przemek19** [comment]
Podmiankę musisz zrobić sam, a ustawiasz w lss-vehicles w vehicles.lua z tego co kojarzę. Będzie tam taka tablica i dodajesz takie coś: [IDPOJAZDU] = {0.4,0,1}, i dostosowujesz to zmieniając cyferki. Ostatnie to wysokość koguta, a reszta to położenie pionowe i poziome.
