### ISSUE TITLE
Nie mogę dać sobie admina

### ISSUE THREAD

**Issue by mati216PL** [lpiob/MTA-XyzzyRP#418]
Witam, po zainstalowaniu skryptu nie mogę sobie dać admina.
Dodawałem konto w ACL przy wyłączonym serwerze, dodawałem konta w konsoli /addaccount i dalej nic.
Mam w konsoli błąd ale nie wiem co on znaczy : 
WARNING: [XyzzyRP]/lss-core/utils.lua:72: Bad argument @ 'isObjectInACLGroup' [Expected acl-group at argument 2, got boolean]

**Comment by Dzender** [comment]
Przy dodawaniu konta na admina upewnij się pierw czy dobrze podłączasz i czy masz wyłączony serwer te 2 punkty są najważniejsze oraz włącz skrypt /start admin i powinno wszystko śmigać ;)

**Comment by mati216PL** [comment]
Zrobione! Dzięki :1st_place_medal:
