### ISSUE TITLE
Nie Ma Komendy Przecho + Kajdanki

### ISSUE THREAD

**Issue by seba14351** [lpiob/MTA-XyzzyRP#424]
1.Nie Ma Komendy Przecho
2.Kajdanki się bugują.
.

**Comment by KIUPIK** [comment]
1. to nie wiem powinna chyba być
2. No to kup wersji XyzzyRP z ostatniej reaktywacji

**Comment by seba14351** [comment]
Jak Mam Kupić XyzzyRP z ostatniej reaktywacji ?

**Comment by KIUPIK** [comment]
Dam ci kontakt ale to kosztuje około 100 złotych po też chciałem kupić

**Comment by seba14351** [comment]
Nom to Daj Jak Korzystasz ze  skype to mój skype się nazywa skype:seba123624
No Chyba że jakoś do gadamy się przez TeamSpeak'a

**Comment by KIUPIK** [comment]
Ja już ci zaproszenie na Skype wysłałem

**Comment by seba14351** [comment]
Wejdz Na Skype
