### ISSUE TITLE
Nie mogę tworzyć pojazdów

### ISSUE THREAD

**Issue by KubaSLP** [lpiob/MTA-XyzzyRP#459]
Witam,mam problem a mianowicie nie mogę tworzyć pojazdów ponieważ,gdy piszę sv pisze że nie mam miejsca w ekwipunku choć je mam nie mam pojęcia co robić pomoże ktoś?
A i drugie pytanie klikając na pojazd nie ma kompletnej interakcji z pojazdem po prostu nic,nic się nie pojawia.
Po trzecie:Istnieje jakiś skrypt żeby dodać pod tabem do interakcji pojazdu przeniesienie go do przechowalni?

**Comment by KubaSLP** [comment]
Do 1 wyskakuje mi coś takiego :[19-01-13 23:31:15] INFO: Operacja na ekwipunku gracza, ktory nie ma zarejestrowanego ekwipunku!

**Comment by KubaSLP** [comment]
Problem 1 rozwiązany

**Comment by KubaSLP** [comment]
2 problem rozwiązany

**Comment by sobek32** [comment]
Podaj ip serwa na PW lub Dsc sobek12#6895

**Comment by KubaSLP** [comment]
Zaprosiłem sobek na dsc a kolejna sprawa to jak przywrócić oryginalną mapę bez utraty sm itd itp. Już wszystkie te poradniki które tam były przestudiowałem i dalej nici
Kolejny problem ujawnił się po uruchomieniu skryptu wb-drzwi a mianowicie nagle przy wjeździe do Parkingu podziemnego PD ujawnia się szara podłoga która blokuje cały wjazd

**Comment by Marquuu** [comment]
Vespee.#4568 - Zapraszam do mnie na pw discord oferuję pomoc.

**Comment by KubaSLP** [comment]
Zamykam,wszystko prócz mapy zrobiłem.PS jeśli ktoś by nie wiedział jak pozbyć się kamieni z drogi ls-lv 
Skrypt:wb-rozbudowane
Kamienie na bazie SM:wb-wysypisko_śmieci
