### ISSUE TITLE
Koguty

### ISSUE THREAD

**Issue by xSaintOGx** [lpiob/MTA-XyzzyRP#517]
Wie ktoś jak dodać koguty/syreny np do sultana?

**Comment by luki19982407** [comment]
Witam, 
O ile dobrze pamiętam dodaje się poprzez baze danych w tabeli lss_vehicles = koguty z 0 na 1

**Comment by xSaintOGx** [comment]
Właśnie tak zrobiłem i dostaje coś takiego: https://ibb.co/xgv8vcg
Wie ktoś jak to naprawić?

**Comment by xSaintOGx** [comment]
Z neonami jest tak samo.

**Comment by xSaintOGx** [comment]
Już mi miły pan odpowiedział, zamykam.
