### ISSUE TITLE
Kolor Markerów Logowania Do Frakcji.

### ISSUE THREAD

**Issue by Skaza16** [lpiob/MTA-XyzzyRP#518]
Witam, czy jest możliwość zmiany koloru markeru logowania do frakcji? Z góry dziękuję za każdą odpowiedź,

**Comment by piotr172** [comment]
W pliku resources/[XyzzyRP]/lss-frakcje/frakcje_c.lua.
Linijka 102:
v.marker=createMarker(v[1],v[2],v[3], "cylinder", 1, 255,255,255)

**Comment by Skaza16** [comment]
Dziękuje Bardzo. Zamykam.
