### ISSUE TITLE
Inne Komendy Admin

### ISSUE THREAD

**Issue by xNinja-z** [lpiob/MTA-XyzzyRP#77]
Czy są jakieś inne ukryte komendy admina np. na teleportowanie auta do siebie, bo prawym i na auto na określoną odległość można. ?? Jeśli są jakieś komendy, które nie są napisanie to proszę o szybka odpowiedz.
Z Góry Dzięki :)

**Comment by Kubus6969** [comment]
A może ktoś wie, gdzie to wgrac bo wgralem to do lss-admin/commands_support.lua i commands_support_c.lua
